# Generated by Django 2.2.1 on 2019-10-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20191025_0444'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
