# Generated by Django 2.2.1 on 2019-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20191025_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.TextField(max_length=100),
        ),
    ]
