version: '3'  
services:  
  nginx:
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: web_app
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file: 
      - .postgres.env.list
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis:alpine
    container_name: redis_app
    ports:
      - "6379:6379"
 
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db 
    ports:
      - "5050:80"
    expose: 
      - "5050"
    env_file: 
      - .pgadmin.env.list
    volumes: 
      - pgadmin_data:/var/lib/pgadmin/data/
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
