# Generated by Django 2.2.1 on 2020-04-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20191208_2047'),
    ]

    operations = [
    ]
