# Generated by Django 2.2.1 on 2019-10-25 04:29

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True)),
                ('photo_profile', models.ImageField(blank=True, upload_to=artists.models.user_directory_path)),
            ],
        ),
    ]
