# Generated by Django 2.2.1 on 2019-10-25 04:59

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20191025_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo_profile',
            field=models.ImageField(upload_to=artists.models.user_directory_path),
        ),
    ]
