# Generated by Django 2.2.1 on 2019-10-25 05:02

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20191025_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to=artists.models.user_directory_path),
        ),
    ]
